name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull superset
        run: git clone https://github.com/apache/superset.git
      - name: Build the stack
        run: docker-compose up -d
