name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull superset
        run: git clone https://github.com/apache/superset.git
      - name: Build the stack
        env:
          FINNHUB_API_KEY=${{secrets.FINNHUB_API_KEY}}
          ZOOKEEPER_IMAGE=${{ZOOKEEPER_IMAGE}}
          ZOOKEEPER_PORTS=${{ZOOKEEPER_PORTS}}
          ZOOKEEPER_CLIENT_PORT=${{ZOOKEEPER_CLIENT_PORT}}
          ZOOKEEPER_TICK_TIME=${{ZOOKEEPER_TICK_TIME}}
          KAFKA_IMAGE=${{KAFKA_IMAGE}}
          KAFKA_PORTS=${{KAFKA_PORTS}}
          KAFKA_INTERNAL_PORT=${{KAFKA_INTERNAL_PORT}}
          KAFKA_TOPIC_DEFAULT=${{KAFKA_TOPIC_DEFAULT}}
          REPLICATION_FACTOR_DEFAULT=${{REPLICATION_FACTOR_DEFAUL}}
          PARTITIONS_DEFAULT=${{PARTITIONS_DEFAULT}}
          KAFDROP_IMAGE=${{KAFDROP_IMAGE}}
          KAFDROP_PORTS=${{KAFDROP_PORTS}}
          WEBSOCKET_PORTS=${{WEBSOCKET_PORTS}}
          PYSPARK_CLIENT_PORTS=${{PYSPARK_CLIENT_PORTS}}
          CASSANDRA_PORTS=${{CASSANDRA_PORTS}}
          CASSANDRA_WEBUI_IMAGE=${{CASSANDRA_WEBUI_IMAGE}}
          CASSANDRA_WEBUI_PORTS=${{CASSANDRA_WEBUI_PORTS}}
          PRESTO_PORTS=${{PRESTO_PORTS}}
          SPARK_IMAGE=${{SPARK_IMAGE}}
          SPARK_MASTER_PORTS=${{SPARK_MASTER_PORTS}}
          SPARK_MASTER_INTERNAL_PORTS=${{SPARK_MASTER_INTERNAL_PORTS}}
          SPARK_MASTER_INTERNAL_PORT=${{SPARK_MASTER_INTERNAL_PORT}}
          SPARK_WORKER_PORTS=${{SPARK_WORKER_PORTS}}
          SPARK_WORKER_CORES=${{SPARK_WORKER_CORES}}
          SPARK_WORKER_MEMORY=${{SPARK_WORKER_MEMORY}}
          COMPOSE_PROJECT_NAME=${{COMPOSE_PROJECT_NAME}}
          DATABASE_DB=${{DATABASE_DB}}
          DATABASE_HOST=${{DATABASE_HOST}}
          DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}
          DATABASE_USER=${{DATABASE_USER}}
          DATABASE_PORT=${{DATABASE_PORT}}
          DATABASE_DIALECT=${{DATABASE_DIALECT}}
          POSTGRES_DB=${{POSTGRES_DB}}
          POSTGRES_USER=${{POSTGRES_USER}}
          POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
          PYTHONPATH=${{PYTHONPATH}}
          REDIS_HOST=${{REDIS_HOST}}
          REDIS_PORT=${{REDIS_PORT}}
          FLASK_ENV=${{FLASK_ENV}}
          SUPERSET_ENV=${{SUPERSET_ENV}}
          SUPERSET_LOAD_EXAMPLES=${{SUPERSET_LOAD_EXAMPLES}}
          SUPERSET_SECRET_KEY=${{secrets.SUPERSET_SECRET_KEY}}
          CYPRESS_CONFIG=${{CYPRESS_CONFIG}}
          SUPERSET_PORT=${{SUPERSET_PORT}}
        run: docker-compose up -d
