name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull superset
        run: git clone https://github.com/apache/superset.git
      - name: Build the stack
        env:
          FINNHUB_API_KEY: ${{secrets.FINNHUB_API_KEY}}
          ZOOKEEPER_IMAGE: ${{secrets.ZOOKEEPER_IMAGE}}
          ZOOKEEPER_PORTS: ${{secrets.ZOOKEEPER_PORTS}}
          ZOOKEEPER_CLIENT_PORT: ${{secrets.ZOOKEEPER_CLIENT_PORT}}
          ZOOKEEPER_TICK_TIME: ${{secrets.ZOOKEEPER_TICK_TIME}}
          KAFKA_IMAGE: ${{secrets.KAFKA_IMAGE}}
          KAFKA_PORTS: ${{secrets.KAFKA_PORTS}}
          KAFKA_INTERNAL_PORT: ${{secrets.KAFKA_INTERNAL_PORT}}
          KAFKA_TOPIC_DEFAULT: ${{secrets.KAFKA_TOPIC_DEFAULT}}
          REPLICATION_FACTOR_DEFAULT: ${{secrets.REPLICATION_FACTOR_DEFAUL}}
          PARTITIONS_DEFAULT: ${{secrets.PARTITIONS_DEFAULT}}
          KAFDROP_IMAGE: ${{secrets.KAFDROP_IMAGE}}
          KAFDROP_PORTS: ${{secrets.KAFDROP_PORTS}}
          WEBSOCKET_PORTS: ${{secrets.WEBSOCKET_PORTS}}
          PYSPARK_CLIENT_PORTS: ${{secrets.PYSPARK_CLIENT_PORTS}}
          CASSANDRA_PORTS: ${{secrets.CASSANDRA_PORTS}}
          CASSANDRA_WEBUI_IMAGE: ${{secrets.CASSANDRA_WEBUI_IMAGE}}
          CASSANDRA_WEBUI_PORTS: ${{secrets.CASSANDRA_WEBUI_PORTS}}
          PRESTO_PORTS: ${{secrets.PRESTO_PORTS}}
          SPARK_IMAGE: ${{secrets.SPARK_IMAGE}}
          SPARK_MASTER_PORTS: ${{secrets.SPARK_MASTER_PORTS}}
          SPARK_MASTER_INTERNAL_PORTS: ${{secrets.SPARK_MASTER_INTERNAL_PORTS}}
          SPARK_MASTER_INTERNAL_PORT: ${{secrets.SPARK_MASTER_INTERNAL_PORT}}
          SPARK_WORKER_PORTS: ${{secrets.SPARK_WORKER_PORTS}}
          SPARK_WORKER_CORES: ${{secrets.SPARK_WORKER_CORES}}
          SPARK_WORKER_MEMORY: ${{secrets.SPARK_WORKER_MEMORY}}
          COMPOSE_PROJECT_NAME: ${{secrets.COMPOSE_PROJECT_NAME}}
          DATABASE_DB: ${{secrets.DATABASE_DB}}
          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_USER: ${{secrets.DATABASE_USER}}
          DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          DATABASE_DIALECT: ${{secrets.DATABASE_DIALECT}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          PYTHONPATH: ${{secrets.PYTHONPATH}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          REDIS_PORT: ${{secrets.REDIS_PORT}}
          FLASK_ENV: ${{secrets.LASK_ENV}}
          SUPERSET_ENV: ${{secrets.SUPERSET_ENV}}
          SUPERSET_LOAD_EXAMPLES: ${{secrets.SUPERSET_LOAD_EXAMPLES}}
          SUPERSET_SECRET_KEY: ${{secrets.SUPERSET_SECRET_KEY}}
          CYPRESS_CONFIG: ${{secrets.CYPRESS_CONFIG}}
          SUPERSET_PORT: ${{secrets.SUPERSET_PORT}}
        run: docker-compose up -d
